-- Replace technical local UUIDs with readable IDs generated by the backend.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = current_schema()
      AND table_name = 'tripjack_hotel_bookings'
      AND column_name = 'booking_id'
      AND data_type = 'uuid'
  ) THEN
    ALTER TABLE tripjack_hotel_bookings
      ALTER COLUMN booking_id TYPE TEXT USING booking_id::text;
  END IF;
END $$;

ALTER TABLE tripjack_hotel_bookings
  ALTER COLUMN booking_id DROP DEFAULT;

CREATE SEQUENCE IF NOT EXISTS tripjack_hotel_booking_seq
  AS BIGINT
  START WITH 1
  INCREMENT BY 1;

UPDATE tripjack_hotel_bookings
SET booking_id = upper(regexp_replace(current_schema(), '^tenant_', ''))
                 || '-HB-' || lpad(nextval('tripjack_hotel_booking_seq')::text, 6, '0')
WHERE booking_id !~ '^[A-Z0-9_-]+-HB-[0-9]{6,}$';
